name: Publish NGINX Image 

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '0 0 1 * *'  # 每个月的1号00:00（UTC时间）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest versions
        id: get_versions
        run: |
          echo "NGINX_VERSION=$(curl -s https://api.github.com/repos/nginx/nginx/releases/latest | grep -oP '"tag_name": "\K[^"]+' | sed 's/release-//')" >> $GITHUB_ENV
          echo "ZSTD_VERSION=$(curl -s https://api.github.com/repos/facebook/zstd/releases/latest | grep -oP '"tag_name": "\K[^"]+' | sed 's/v//')" >> $GITHUB_ENV
          echo "CORERULESET_VERSION=$(curl -s https://api.github.com/repos/coreruleset/coreruleset/releases/latest | grep -oP '"tag_name": "\K[^"]+' | sed 's/v//')" >> $GITHUB_ENV

      - name: Build and push NGINX image 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nginx/Dockerfile-waf
          push: true
          tags: kjlion/nginx:alpine
          platforms: linux/amd64,linux/arm64
          build-args: |
            NGINX_VERSION=${{ env.NGINX_VERSION }}
            ZSTD_VERSION=${{ env.ZSTD_VERSION }}
            CORERULESET_VERSION=${{ env.CORERULESET_VERSION }}
